[build]
  publish = "frontend"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/icon-192.png"
  status = 200